# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 10:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0003_notifications_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='hood',
            field=tinymce.models.HTMLField(default='Nairobi'),
        ),
    ]
