# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0005_auto_20191202_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.Hood')),
            ],
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='priority',
        ),
        migrations.AlterField(
            model_name='business',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
