# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_app', '0006_auto_20191202_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='healthlogo/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_app.Hood')),
            ],
        ),
    ]
